Task dev6
alexandramila/GIT-1 pull request #9
Opened 2017-06-29 14:39 UTC by alexandramila

2017-06-29 14:45 UTC, AlexanderSoroka requested changes
Please, follow the rule "one class - one java file"

2017-06-29 19:01 UTC, AlexanderSoroka requested changes

2017-06-29 19:01 UTC, AlexanderSoroka commented on CheckSequence.java
> +  public static void checkNondecreasing(String[] gaps) {
Why static?

2017-06-29 19:01 UTC, AlexanderSoroka commented on CheckSequence.java
> + * @param gaps the sequence that was entered by the user
class doesn't have any params

2017-06-29 19:01 UTC, AlexanderSoroka commented on CheckSequence.java
> +  public static void checkNondecreasing(String[] gaps) {
missed javadoc

2017-07-03 16:01 UTC, alexandramila commented on CheckSequence.java
> + * @param gaps the sequence that was entered by the user
I've changed the javadoc for a method, but it still shows this comment. I don't understand what is wrong and where is mistake.

2017-07-03 20:22 UTC, AlexanderSoroka requested changes

2017-07-03 20:22 UTC, AlexanderSoroka commented on CheckSequence.java
> +/**
indentation is wrong

2017-07-03 20:22 UTC, AlexanderSoroka commented on CheckSequence.java
> +      return;
useless return

2017-07-03 20:22 UTC, AlexanderSoroka commented on CheckSequence.java
> +          System.out.println("Your numerical sequence is not non-decreasing.");
single responsibility violation - method must check (1 responsibility), not "check, verify & output" (3 responsibility)

2017-07-03 20:22 UTC, AlexanderSoroka commented on ReadFromConsole.java
> + * @return true  when the data has been entered
if I'm not mistaken only one @return is allowed

2017-07-03 20:22 UTC, AlexanderSoroka commented on ReadFromConsole.java
> +    if (args.length != 0) {
return (args.length != 0);

2017-07-03 20:22 UTC, AlexanderSoroka commented on ReadFromConsole.java
> +  public boolean read(String[] args) {
unsuitable method name

2017-07-04 15:21 UTC, AlexanderSoroka requested changes

2017-07-04 15:21 UTC, AlexanderSoroka commented on ReadFromCommandLine.java
> +class ReadFromCommandLine {
Wrong class name - you cannot read from command line, you can either receive command line arguments either read from console

2017-07-04 15:21 UTC, AlexanderSoroka commented on ReadFromCommandLine.java
> +    if (args.length != 0) {
single responsibility violation - reading and checking in one method

2017-07-04 15:21 UTC, AlexanderSoroka commented on ReadFromConsole.java
> +    return gaps;
return s.split(" ");

2017-07-04 17:14 UTC, alexandramila commented on ReadFromCommandLine.java
> +    if (args.length != 0) {
I'm not sure about hpw can I do this.

2017-07-05 19:50 UTC, AlexanderSoroka approved these changes

2017-07-05 19:50 UTC, AlexanderSoroka commented on CommandLineArguments.java
> +  public String[] sequenceCommandLine(String[] args) {  // to do - divided into two methods
Please, do it before merging to master

2018-01-08 21:45 UTC, merged